# Generated by Django 5.0.6 on 2024-05-15 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="name",
            field=models.CharField(
                default="",
                help_text="Введите название товара",
                max_length=250,
                verbose_name="наименование",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="version",
            name="product_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
                verbose_name="наименование",
            ),
        ),
    ]
