# Generated by Django 4.2 on 2024-05-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["product_name"],
                "permissions": [
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_category", "Can edit Category"),
                    ("can_edit_product_activ", "Can edit Product_activ"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_activ",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="признак публикации"
            ),
        ),
    ]
