# Generated by Django 4.2 on 2024-05-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_options_product_product_activ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_activ",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="признак публикации"
            ),
        ),
    ]
